services:
  pico:
    container_name: pico
    build:
      context: .
      dockerfile: docker/Dockerfile
    init: true
    shm_size: "1gb"
    restart: unless-stopped
    working_dir: /root/.pico/agent
    volumes:
      - ${HOME}/.pico:/root/.pico
      - ${HOME}/.omp:/root/.omp
      - /var/run/docker.sock:/var/run/docker.sock
      - pico-supervisor:/root/.pico/supervisor
      - pico-build:/build

volumes:
  pico-supervisor:
  pico-build:
